[package]
name = "generate-telegram-api"
version = "0.1.0"
authors = ["ccQpein"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
Crawler={path = "../Crawler"}
curl = "0.4.34"
