[package]
name = "Axum-test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.2.0"
tokio = { version = "1", features = ["full"] }