[package]
name = "winit-new-tabs-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = { git = "https://github.com/amrbashir/winit.git" }
