[package]
name = "lisp-rpc-rust-parser"
version = "0.1.0"
edition = "2024"

# [lib]
# crate-type = ["cdylib"]

[dependencies]
itertools = "0"
tracing = "0"
tracing-subscriber = { version = "0", features = ["env-filter"] }
