//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "chat_records")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub space_type: String,
    pub space_id: String,
    pub message_id: String,
    pub reply_to: Option<String>,
    pub role: String,
    pub content: Option<String>,
    pub create_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
