//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

pub use super::chat_records::Entity as ChatRecords;
pub use super::gpt_group_whitelist::Entity as GptGroupWhitelist;
pub use super::gpt_white_list::Entity as GptWhiteList;
pub use super::reminder::Entity as Reminder;
