// Include the constant generated by build.rs
include!(concat!(env!("OUT_DIR"), "/constants.rs"));

// A large dataset size, 64M
const DATA_SIZE: usize = 64 * 1024 * 1024;

pub fn sequential_access_step4(data: &mut [i32]) {
    for i in (0..data.len()).step_by(4) {
        data[i] = 1;
    }
}

pub fn sequential_access_step16(data: &mut [i32]) {
    for i in (0..data.len()).step_by(16) {
        data[i] = 1;
    }
}

// Helper to create data for the benchmark
pub fn create_data() -> Vec<i32> {
    vec![0; DATA_SIZE]
}
