[package]
name = "quic-test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quiche = "0.8.1"
log = "0.4"
env_logger = "0.8"
mio = "0.6"
ring = "0.16"