[package]
name = "learn-wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.28"
env_logger = "0.10"
log = "0.4"
wgpu = "0.18"
cfg-if = "1.0.0"
tokio = { version = "1", features = ["full"] }
