(ql:quickload "grpc")
(grpc:init-grpc)

;; protobufs support
(ql:quickload "cl-protobufs")

;; load the lisp generated by
(load "./hello-world.lisp")

(grpc:with-insecure-channel (channel "localhost:9091")
  ;;(format t "~a~%" channel)
  (let* ((request (CL-PROTOBUFS.HELLO:make-hello-request
				   :client-type "lisp"
				   :message-body "hello from common lisp client"))
		 (response (CL-PROTOBUFS.HELLO-RPC:call-say-hello channel request))
		 )
	(format t "~a~%" response)
	))

;; (grpc:with-ssl-channel (channel ("localhost:9091"
;; 								 (:pem-root-certs "")
;; 								 )))

;;:= ssl channel maybe in future
