* Arch

** plugin
howebrew stuff can be plugin

** recept
all package receipts location.

** libs
all lisp files of this project

** db
need think about the way to store the packages. the way should be flexible, can change in config (or the standalone helper plugin)

* system

** common lisp version

+ sbcl
+ etc. (need feature flags for it)

** config path
default is ~~/.config/xxx~, can change with env var.

in ~config.lisp~

* interface

** shell interface
ask question about inplenments, config path, or something else

* homebrew receipt translater

* install 
install script. Python script? because most system has python installed.

minimize lisp image download? and install quicklisp and sbcl release version and replaced?

need keep latest version? (in case the newest sbcl has issue). Or just keep the image pre-build for espresso.

* todo list

- [X] need command output async-able (maybe give additional thread?)
- [ ] shell inaction ~-h~
+- [ ] receipt need its own output stream+
- [X] need to find the way how to manage the reciepts pakcages, file, and receipts (version like homebrew?)
- [-] config
  - [X] default receipts location
  - [ ] custome receipts locations
  - [ ] should have ability to change when install (install script)
- [X] reciept template
- [ ] install script
  - [ ] sbcl
  - [ ] change config setting
  - [ ] ros need to be replaced because it install via homebrew
- [ ] Alias (or something else) can handle the scripts of commmands
- [ ] more output, like which dir we are in, which folder we are deleting
- [X] delete rename to uninstall?
- [ ] reinstall & clean command/receipt slots

